-- +migrate Up
CREATE TABLE product (
    id BIGSERIAL PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- +migrate Down
DROP TABLE IF EXISTS product;